require "user.colorscheme"
require "user.keymaps"
require "user.options"

require "plugins.alpha"
require "plugins.autocommands"
require "plugins.autopairs"
require "plugins.bufferline"
require "plugins.cmp"
require "plugins.comment"
require "plugins.copilot"
require "plugins.dap"
require "plugins.gitsigns"
require "plugins.impatient"
require "plugins.indentline"
-- require "plugins.lsp"
require "plugins.lualine"
require "plugins.luasnip"
require "plugins.nvim-tree"
require "plugins.plugins"
require "plugins.project"
require "plugins.telescope"
require "plugins.toggleterm"
require "plugins.treesitter"
require "plugins.vimtex"
